### ISSUE TITLE
Getting a mask with segment labels

### ISSUE THREAD

**Issue by carlosgmartin** [mstorath/Pottslab#3]
Is there a way to get an integer mask indicating the unique segment each pixel belongs to? That is, two pixels may end up with the same color in the Potts segmentation but, if they do not belong to the same contiguous region, should receive different labels. This is the result returned by the [scikit image](https://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.felzenszwalb) segmentation algorithms, for example.

**Comment by carlosgmartin** [comment]
The python function [`skimage.measure.label`](https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.label) does this. There's also a matlab function called [`bwlabel`](https://www.mathworks.com/help/images/ref/bwlabel.html) that does this, but only for binary images.

**Comment by mstorath** [comment]
Hi Carlos, I have added the Matlab function "segToLabel". Please let me know if it works for you. Best, Martin

**Comment by carlosgmartin** [comment]
Thanks. Is it possible to use this with pottslab-standalone.jar?

I also have another question: Is it possible to control the number of iterations when using pottslab-standalone.jar? More generally, are there any other command-line arguments that can be passed to it?

**Comment by mstorath** [comment]
The implementation uses Matlab functions, so it can't be used with pottslab-standalone.jar at the moment. However, you could use a simple postprocessing to get a label image: iterate through each pixel of the image and perform a flood fill with integers (fill with 0 in the first segment, with 1 for the second and so on)
